name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/checkout@v2
      - name: Compile Paper
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: paper
          root_file: 1901_3230880_philip_heltweg.tex
      - name: Compile Presentation
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: presentation
          root_file: 1901_3230880_philip_heltweg_presentation.tex
      - name: Upload Paper
        uses: actions/upload-artifact@v2
        with:
          name: 1901_3230880_philip_heltweg.pdf
          path: paper/1901_3230880_philip_heltweg.pdf
      - name: Upload Presentation
        uses: actions/upload-artifact@v2
        with:
          name: 1901_3230880_philip_heltweg_presentation.pdf
          path: presentation/1901_3230880_philip_heltweg_presentation.pdf