name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/checkout@v2
      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            paper/1901_3230880_philip_heltweg.tex
            presentation/1901_3230880_philip_heltweg_presentation.tex
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path:  |
            paper/1901_3230880_philip_heltweg.pdf
            presentation/1901_3230880_philip_heltweg_presentation.pdf